config/routes.rb
Rails.application.routes.draw do
    root to: "toppages#index"
    
    get "signup", to: "users#new"
    resources :users, only: [:show, :new, :create]
    
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    
    get "housework_list", to: "houseworks#index"
    resources :houseworks, only: [:new, :create, :destroy]
    
    resources :housework_schedules, only: [:new, :create, :destroy]
    
    resources :relationships, only: [:create, :update, :destroy]
    
    resources :contacts, only: [:new, :create]
end

app/models/housework.rb
class Housework < ApplicationRecord
  belongs_to :user
  has_many :housework_schedules, dependent: :destroy
  
  validates :category, presence: true, length: {maximum: 50}
  validates :name, presence: true, length: {maximum: 50}
  validates :goal, presence: true
  validates :frequency, presence: true, length: {maximum: 255}
end

app/controllers/houseworks_controller.rb
class HouseworksController < ApplicationController
  before_action :correct_user, only: [:destroy]
  before_action :require_user_logged_in

  
  def index
  end

  def new
    @housework = current_user.houseworks.build
    @current_user_houseworks = current_user.houseworks.order(id: :desc).page(params[:page])
    @partner_houseworks = partner&.houseworks&.order(id: :desc)&.page(params[:page])
    @wd = ["日", "月", "火", "水", "木", "金", "土"]
  end

  def create
    @housework = current_user.houseworks.build(housework_params)
    if @housework.save
      flash[:success] = "家事を登録しました。"
      redirect_to new_housework_url
    else
      flash.now[:danger] = "家事の登録に失敗しました。"
      render :new
    end
  end
    
  
  def destroy
    @current_user_housework.destroy
    flash[:success] = "家事分担リストから削除しました"
    redirect_to new_housework_url
  end
  
  private
  
  def housework_params
    params.require(:housework).permit(:category, :name, :goal, :frequency)
  end
  
  def correct_user
    @current_user_housework = current_user.houseworks.find_by(id: params[:id])
    unless @current_user_housework
      redirect_to root_url
    end
  end
  
end

app/views/houseworks/_current_user_houseworks.html.erb
<table class="table table-sm table-bordered">
    <thead>
        <tr class="table-active">
            <th class="text-center">項目</th>
            <th class="text-center">目標</th>
            <th class="text-center">頻度</th>
            <th></th>
        </th>
    </thead>
    <tbody>
        <% current_user_houseworks.each do |current_user_housework| %>
            <tr>
                <th><%= current_user_housework.name %></th>
                <th><%= current_user_housework.goal %>回</th>
                <th><%= current_user_housework.frequency %></th>
                <th><%= link_to "削除", housework_path(current_user_housework), data: { confirm: "本当に削除しますか？" }, class: "btn btn-sm btn-danger", method: :delete %></th>
            </tr>
        <% end %>                
    </tbody>
</table>

app/views/houseworks/_partner_houseworks.html.erb
<table class="table table-sm table-bordered">
    <thead>
        <tr class="table-active">
            <th class="text-center">項目</th>
            <th class="text-center">目標</th>
            <th class="text-center">頻度</th>
        </th>
    </thead>
    <tbody>
        <% partner_houseworks&.each do |partner_housework| %>
            <tr>
                <th><%= partner_housework.name %></th>
                <th><%= partner_housework.goal %>回</th>
                <th><%= partner_housework.frequency %></th>
            </tr>
        <% end %>                
    </tbody>
</table>

app/views/houseworks/new.html.erb
<div class="container">
    <div class="text-center pt-5 mb-5">
        <h1>家事分担リスト</h1>
    </div>
    
    <div class="row">
        <div class="col-sm-4">
            <h3>家事の追加</h3>
    
            <%= form_with(model: @housework, local: true) do |f|  %>
                <%= render "layouts/error_messages", model: f.object %>
            
                <div class="form-group">
                    <%= f.label :category, "カテゴリ" %>
                    <%= f.text_field :category, class: "form-control" %>
                </div>
                
                <div class="form-group">
                    <%= f.label :name, "項目" %>
                    <%= f.text_field :name, class: "form-control" %>
                </div>
                
                <div class="form-group">
                    <%= f.label :goal, "目標" %>
                    <%= f.number_field :goal, class: "form-control" %>
                </div>
                
                <div class="form-group">
                    <%= f.label :frequency, "頻度" %>
                    <%= f.text_field :frequency, class: "form-control" %>
                </div>
                
                <%= f.submit "追加", class: "btn btn-primary btn-block" %>
            <% end %>
        </div>
        
        <div class="col-sm-8">
            <%= render "users/current_user" %>
            <%= render "current_user_houseworks", current_user_houseworks: @current_user_houseworks %>
            
            <%= render "users/partner" %>
            <%= render "partner_houseworks", partner_houseworks: @partner_houseworks %>
        </div>
        
    </div>
</div>