config/routes.rb
Rails.application.routes.draw do
    root to: "toppages#index"
    
    get "signup", to: "users#new"
    resources :users, only: [:show, :new, :create]
    
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    
    get "housework_list", to: "houseworks#index"
    resources :houseworks, only: [:new, :create, :destroy]
    
    resources :housework_schedules, only: [:new, :create, :destroy]
    
    resources :relationships, only: [:create, :update, :destroy]
    
    resources :contacts, only: [:new, :create]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>        
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<%= stylesheet_link_tag "footer/footer.css", :media => "all" %>

<footer>
    <div class="container-fluid px-5 py-5">
        <div class="text-center">
            <img class="footer-logo" src="/assets/1_Primary_logo_on_transparent_143x73.png"></img>
            <h5>&copy; KAJUAL</h5>
        </div>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "header/navbar.css", :media => "all" %>

<header class="sticky-top">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><img class="header-logo"src="/assets/1_Primary_logo_on_transparent_143x73.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportContent">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <% if logged_in? %>
                    <li class="nav-item"><%= link_to "家事分担リスト", new_housework_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "スケジュール", new_housework_schedule_path, class: "nav-link" %></li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" ><%= current_user.name%></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item"><%= link_to "ユーザ情報", user_path(current_user) %></li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete %></li>
                        </ul>
                    </li>
                <% else %>
                    <li class="nav-item"><%= link_to "会員登録", signup_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>    

app/views/layouts/_navbar_toppages.html.erb
<%= stylesheet_link_tag "header/navbar.css", :media =>     "all" %>

<header class="fixed-top">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><img class="header-logo"src="/assets/1_Primary_logo_on_transparent_143x73.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportContent">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <% if logged_in? %>
                    <li class="nav-item"><%= link_to "家事分担リスト", new_housework_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "スケジュール", new_housework_schedule_path, class: "nav-link" %></li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" ><%= current_user.name%></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item"><%= link_to "ユーザ情報", user_path(current_user) %></li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete %></li>
                        </ul>
                    </li>
                <% else %>
                    <!--アプリ用2-->
                    <!--<li class="nav-item"><%= link_to "会員登録", signup_path, class: "nav-link" %></li>-->
                    <!--<li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>-->
                    <!--LP用2-->
                    <li class="nav-item"><%= link_to "会員登録", root_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ログイン", root_path, class: "nav-link" %></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Kajual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
      <%= render "layouts/navbar" %>
    
      <%= render "layouts/flash_messages" %>
      
      <%= yield %>
  </body>
</html>

app/views/layouts/application_toppages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Kajual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
    <!--Twitterカード用-->
    <meta name="twitter:card" content="summary_large_image"> <!--①-->
    <meta name="twitter:site" content="@yu_fe_101208" /> <!--②-->
    <meta property="og:url" content="https://kajual.herokuapp.com/" /> <!--③-->
    <meta property="og:title" content="自作Webアプリ -KAJUAL-" /> <!--④-->
    <meta property="og:description" content="KAJUALは家事達成度共有アプリです。" /> <!--⑤-->
    <meta property="og:image" content="https://kajual.herokuapp.com//assets/the-creative-exchange-cpIgNaazQ6w-unsplash.jpg" /> <!--⑥-->
  </head>

  <body>
      <%= render "layouts/navbar_toppages" %>
    
      <%= render "layouts/flash_messages" %>
      
      <%= yield %>
      
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>